apiVersion: v1
kind: Service
metadata:
  name: mcpo-tools
  namespace: open-webui
spec:
  selector:
    app: mcpo-tools
  ports:
    - name: http-api
      port: 80
      targetPort: http-api
      protocol: TCP
