apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: test
spec:
  restartPolicy: OnFailure
  containers:
    - name: gpu-container
      image: nvcr.io/nvidia/cuda:12.9.0-base-ubuntu24.04
      command: ["/bin/bash", "-c"]
      args: ["nvidia-smi -L && sleep 3600"]
      resources:
        claims:
        - name: gpu
  # 定義したsingle-gpuのアサイン
  resourceClaims:
  - name: gpu
    resourceClaimTemplateName: single-gpu
